In [1]:
# copy is a new array where view is the view of the original array.
# Any changes made to the copy will not affect original array and vice versa.
# Any changes made to the view will affect the original array and vice versa.

In [2]:
import numpy as np

## Copy

In [3]:
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [4]:
# making a copy of this array and change its values to see the result

In [5]:
a = arr.copy()
print(a)

[1 2 3 4 5]


In [6]:
a[:3]=0
print(a)
print(arr)

[0 0 0 4 5]
[1 2 3 4 5]


In [7]:
# here, changes is made in the copy array but the original array is not affected.

In [8]:
# changing the original array and displaying both arrays

In [9]:
arr[-1] = 50
print(a)
print(arr)

[0 0 0 4 5]
[ 1  2  3  4 50]


In [10]:
# here we can see change is made in the original array but the copy of the array is not affected.

## View

In [11]:
# making the view of array and change its value to see the result 

In [12]:
arr2 = np.arange(50,100,10)
arr2

array([50, 60, 70, 80, 90])

In [13]:
v = arr2.view()
v[0]=100
print(arr2)
print(v)

[100  60  70  80  90]
[100  60  70  80  90]


In [14]:
# here, change is made in the view of the array but original array is also affected

In [15]:
# making a view , changing the orignal array, and displaying both arrays

In [16]:
arr3 = np.array([5,10,15,20,15])
c = arr3.view()
arr3[1:] = 0

print(arr3)
print(c)

[5 0 0 0 0]
[5 0 0 0 0]


In [17]:
# here we can see any changes made to the original array will also affect the view of that array