## 1. Create a 2D array that resembles the matrix below and find its shape
[[11 12 13 14]
[15 16 17 18]]

In [1]:
import numpy as np

In [2]:
l1= np.array([[11,12,13,14],[15,16,17,18]])
print(l1)
print('The shape of thr matrix is :',l1.shape)

[[11 12 13 14]
 [15 16 17 18]]
The shape of thr matrix is : (2, 4)


## 2.Create an array of ones that has 3 rows and 4 columns.

In [3]:
l2 =np.ones((3,4),dtype= int)
print(l2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 3.Create an array containing integers 4 to 13 inclusive

In [4]:
l3= np.arange(4,14)
print(l3)

[ 4  5  6  7  8  9 10 11 12 13]


## 4.Create a 3 by 3 array with random integers in [10, 20]. 

In [5]:
l4 = np.random.randint(10,20, size=(3,3))
print(l4)

[[12 10 18]
 [17 16 18]
 [15 19 19]]


## 5.Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [6]:
l5= np.arange(21)
print(l5)
print(l5[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


## 6.Change all elements in 1st and second row to 0
 [[11,12,13], [14,15,16], [17,18,19]]

In [7]:
l6 = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(l6)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [8]:
l6[:2,:]=0
print(l6)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
