In [1]:
#By reshaping we can add or remove dimensions or change number of elements in each dimension.
# array.reshape(row,column)

## Reshaping from 1-D to 2-D

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1,21)
print(my_arr)
my_arr.shape

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


(20,)

In [4]:
my_arr = my_arr.reshape(4,5)    #multiplication of row and col should be equal to no.of elements in the dimension
print(my_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]



## Reshaping from 1-D to 3-D

In [5]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## Reshaping from 2-D to 3-D

In [7]:
arr2 = np.arange(0,40).reshape(5,8)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [8]:
arr2= arr2.reshape(5,2,-1)    # -1 will automatically calculate the number. it can be used for only one dimension either row/col
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]]])

In [9]:
arr3 = np.arange(20,40).reshape(5,-1)
arr3

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [10]:
arr3 = arr3.reshape(2,-1,2)
arr3

array([[[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

## Reshaping from ndim to 1-D

In [11]:
my_arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [12]:
# changing 2-D to 1-D
twoD_oneD = my_arr.reshape(-1)
print(twoD_oneD)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
arr3

array([[[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [14]:
# Changing 3-D to 1-D
threeD_oneD = arr3.reshape(-1)
print(threeD_oneD)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
